"""initial version

Revision ID: 455e1b63ef60
Revises:
Create Date: 2026-04-18 15:18:35.817271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455e1b63ef60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightning_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('amount_msat', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=160), nullable=True),
    sa.Column('payment_hash', sa.String(length=160), nullable=True),
    sa.Column('payment_request', sa.String(length=4096), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('idempotency_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('incoming', 'outgoing')", name='ck_lightning_invoices_direction_valid'),
    sa.CheckConstraint("provider IN ('lnbits')", name='ck_lightning_invoices_provider_valid'),
    sa.CheckConstraint("status IN ('pending', 'paid', 'expired', 'cancelled', 'failed')", name='ck_lightning_invoices_status_valid'),
    sa.CheckConstraint('amount_msat > 0', name='ck_lightning_invoices_amount_msat_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider_invoice_id')
    )
    op.create_index(op.f('ix_lightning_invoices_direction'), 'lightning_invoices', ['direction'], unique=False)
    op.create_index(op.f('ix_lightning_invoices_expires_at'), 'lightning_invoices', ['expires_at'], unique=False)
    op.create_index(op.f('ix_lightning_invoices_payment_hash'), 'lightning_invoices', ['payment_hash'], unique=False)
    op.create_index(op.f('ix_lightning_invoices_provider'), 'lightning_invoices', ['provider'], unique=False)
    op.create_index(op.f('ix_lightning_invoices_status'), 'lightning_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_lightning_invoices_user_id'), 'lightning_invoices', ['user_id'], unique=False)
    op.create_table('operation_idempotencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('started', 'succeeded', 'failed')", name='ck_operation_idempotencies_status_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation', 'idempotency_key', name='uq_operation_idempotencies_operation_key')
    )
    op.create_index(op.f('ix_operation_idempotencies_operation'), 'operation_idempotencies', ['operation'], unique=False)
    op.create_index(op.f('ix_operation_idempotencies_resource_id'), 'operation_idempotencies', ['resource_id'], unique=False)
    op.create_index(op.f('ix_operation_idempotencies_status'), 'operation_idempotencies', ['status'], unique=False)
    op.create_table('provider_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=160), nullable=True),
    sa.Column('payment_hash', sa.String(length=160), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_detail', sa.String(length=1000), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("provider IN ('lnbits')", name='ck_provider_events_provider_valid'),
    sa.CheckConstraint("status IN ('received', 'processed', 'failed')", name='ck_provider_events_status_valid'),
    sa.ForeignKeyConstraint(['invoice_id'], ['lightning_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_events_event_type'), 'provider_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_provider_events_invoice_id'), 'provider_events', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_provider_events_payment_hash'), 'provider_events', ['payment_hash'], unique=False)
    op.create_index(op.f('ix_provider_events_provider'), 'provider_events', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_events_provider_invoice_id'), 'provider_events', ['provider_invoice_id'], unique=False)
    op.create_index(op.f('ix_provider_events_status'), 'provider_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_events_status'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_provider_invoice_id'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_provider'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_payment_hash'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_invoice_id'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_event_type'), table_name='provider_events')
    op.drop_table('provider_events')
    op.drop_index(op.f('ix_operation_idempotencies_status'), table_name='operation_idempotencies')
    op.drop_index(op.f('ix_operation_idempotencies_resource_id'), table_name='operation_idempotencies')
    op.drop_index(op.f('ix_operation_idempotencies_operation'), table_name='operation_idempotencies')
    op.drop_table('operation_idempotencies')
    op.drop_index(op.f('ix_lightning_invoices_user_id'), table_name='lightning_invoices')
    op.drop_index(op.f('ix_lightning_invoices_status'), table_name='lightning_invoices')
    op.drop_index(op.f('ix_lightning_invoices_provider'), table_name='lightning_invoices')
    op.drop_index(op.f('ix_lightning_invoices_payment_hash'), table_name='lightning_invoices')
    op.drop_index(op.f('ix_lightning_invoices_expires_at'), table_name='lightning_invoices')
    op.drop_index(op.f('ix_lightning_invoices_direction'), table_name='lightning_invoices')
    op.drop_table('lightning_invoices')
    # ### end Alembic commands ###
