"""initial version

Revision ID: 56c79bc45c98
Revises:
Create Date: 2026-04-17 22:44:16.719332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c79bc45c98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('reserved_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("account_type IN ('user', 'game', 'application', 'platform', 'escrow', 'fee')", name='ck_accounts_account_type_valid'),
    sa.CheckConstraint('balance >= 0', name='ck_accounts_balance_non_negative'),
    sa.CheckConstraint('reserved_balance <= balance', name='ck_accounts_reserved_balance_not_greater_than_balance'),
    sa.CheckConstraint('reserved_balance >= 0', name='ck_accounts_reserved_balance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_table('ledger_audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_audit_events_event_type'), 'ledger_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ledger_audit_events_resource_id'), 'ledger_audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_ledger_audit_events_resource_type'), 'ledger_audit_events', ['resource_type'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('idempotency_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reversed_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'posted', 'reversed', 'failed', 'cancelled')", name='ck_ledger_transactions_status_valid'),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('reversed_transaction_id')
    )
    op.create_index(op.f('ix_ledger_transactions_reference_id'), 'ledger_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_reference_type'), 'ledger_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_status'), 'ledger_transactions', ['status'], unique=False)
    op.create_table('operation_idempotencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation', 'idempotency_key', name='uq_operation_idempotencies_operation_key')
    )
    op.create_index(op.f('ix_operation_idempotencies_operation'), 'operation_idempotencies', ['operation'], unique=False)
    op.create_index(op.f('ix_operation_idempotencies_resource_id'), 'operation_idempotencies', ['resource_id'], unique=False)
    op.create_table('balance_holds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('idempotency_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'consumed', 'released', 'expired', 'cancelled')", name='ck_balance_holds_status_valid'),
    sa.CheckConstraint('amount > 0', name='ck_balance_holds_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_balance_holds_account_id'), 'balance_holds', ['account_id'], unique=False)
    op.create_index(op.f('ix_balance_holds_expires_at'), 'balance_holds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_balance_holds_reference_id'), 'balance_holds', ['reference_id'], unique=False)
    op.create_index(op.f('ix_balance_holds_reference_type'), 'balance_holds', ['reference_type'], unique=False)
    op.create_index(op.f('ix_balance_holds_status'), 'balance_holds', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("entry_type IN ('debit', 'credit')", name='ck_ledger_entries_entry_type_valid'),
    sa.CheckConstraint('amount > 0', name='ck_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_reference_id'), 'ledger_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_reference_type'), 'ledger_entries', ['reference_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_reference_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_reference_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_balance_holds_status'), table_name='balance_holds')
    op.drop_index(op.f('ix_balance_holds_reference_type'), table_name='balance_holds')
    op.drop_index(op.f('ix_balance_holds_reference_id'), table_name='balance_holds')
    op.drop_index(op.f('ix_balance_holds_expires_at'), table_name='balance_holds')
    op.drop_index(op.f('ix_balance_holds_account_id'), table_name='balance_holds')
    op.drop_table('balance_holds')
    op.drop_index(op.f('ix_operation_idempotencies_resource_id'), table_name='operation_idempotencies')
    op.drop_index(op.f('ix_operation_idempotencies_operation'), table_name='operation_idempotencies')
    op.drop_table('operation_idempotencies')
    op.drop_index(op.f('ix_ledger_transactions_status'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_reference_type'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_reference_id'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_ledger_audit_events_resource_type'), table_name='ledger_audit_events')
    op.drop_index(op.f('ix_ledger_audit_events_resource_id'), table_name='ledger_audit_events')
    op.drop_index(op.f('ix_ledger_audit_events_event_type'), table_name='ledger_audit_events')
    op.drop_table('ledger_audit_events')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
