"""add destination account to checkout

Revision ID: 91ddb9426907
Revises: c5a45d9c550c
Create Date: 2026-04-21 14:45:24.088345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ddb9426907'
down_revision: Union[str, Sequence[str], None] = 'c5a45d9c550c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('destination_account_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_checkout_sessions_destination_account_id'), 'checkout_sessions', ['destination_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkout_sessions_destination_account_id'), table_name='checkout_sessions')
    op.drop_column('checkout_sessions', 'destination_account_id')
    # ### end Alembic commands ###
