"""create initial hub models

Revision ID: a91e6865a832
Revises:
Create Date: 2026-04-20 17:11:57.413560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91e6865a832'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'revoked')", name='ck_admin_role_assignments_status_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_sub', 'role', name='uq_admin_role_assignments_user_sub_role')
    )
    op.create_index(op.f('ix_admin_role_assignments_role'), 'admin_role_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_admin_role_assignments_status'), 'admin_role_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_admin_role_assignments_user_sub'), 'admin_role_assignments', ['user_sub'], unique=False)
    op.create_table('checkout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.String(length=120), nullable=False),
    sa.Column('order_id', sa.String(length=160), nullable=False),
    sa.Column('amount_msat', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('return_url', sa.String(length=2048), nullable=False),
    sa.Column('cancel_url', sa.String(length=2048), nullable=False),
    sa.Column('checkout_url', sa.String(length=2048), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'settled', 'failed', 'canceled', 'expired')", name='ck_checkout_sessions_status_valid'),
    sa.CheckConstraint('amount_msat > 0', name='ck_checkout_sessions_amount_msat_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'order_id', name='uq_checkout_sessions_game_order')
    )
    op.create_index(op.f('ix_checkout_sessions_expires_at'), 'checkout_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_game_id'), 'checkout_sessions', ['game_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_order_id'), 'checkout_sessions', ['order_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_status'), 'checkout_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_user_id'), 'checkout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkout_sessions_user_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_status'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_order_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_game_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_expires_at'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index(op.f('ix_admin_role_assignments_user_sub'), table_name='admin_role_assignments')
    op.drop_index(op.f('ix_admin_role_assignments_status'), table_name='admin_role_assignments')
    op.drop_index(op.f('ix_admin_role_assignments_role'), table_name='admin_role_assignments')
    op.drop_table('admin_role_assignments')
    # ### end Alembic commands ###
