"""add checkout composition and ledger account mapping

Revision ID: c5a45d9c550c
Revises: a91e6865a832
Create Date: 2026-04-20 17:23:03.145944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a45d9c550c'
down_revision: Union[str, Sequence[str], None] = 'a91e6865a832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ledger_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=False),
    sa.Column('ledger_account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ledger_accounts_ledger_account_id'), 'user_ledger_accounts', ['ledger_account_id'], unique=True)
    op.create_index(op.f('ix_user_ledger_accounts_user_sub'), 'user_ledger_accounts', ['user_sub'], unique=True)
    with op.batch_alter_table('checkout_sessions') as batch_op:
        batch_op.drop_constraint('ck_checkout_sessions_status_valid', type_='check')
        batch_op.add_column(sa.Column('internal_amount_msat', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('external_amount_msat', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ledger_account_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('ledger_hold_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('payment_request', sa.String(length=4096), server_default='', nullable=False))
        batch_op.add_column(sa.Column('invoice_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_checkout_sessions_invoice_expires_at'), ['invoice_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_sessions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_sessions_ledger_account_id'), ['ledger_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_sessions_ledger_hold_id'), ['ledger_hold_id'], unique=False)
        batch_op.create_foreign_key('fk_checkout_sessions_ledger_account_id', 'user_ledger_accounts', ['ledger_account_id'], ['ledger_account_id'])
        batch_op.create_check_constraint(
            'ck_checkout_sessions_status_valid',
            "status IN ('created', 'awaiting_payment', 'reserved', "
            "'settled', 'failed', 'canceled', 'expired')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions') as batch_op:
        batch_op.drop_constraint('ck_checkout_sessions_status_valid', type_='check')
        batch_op.drop_constraint('fk_checkout_sessions_ledger_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_ledger_hold_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_ledger_account_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_invoice_expires_at'))
        batch_op.drop_column('invoice_expires_at')
        batch_op.drop_column('payment_request')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('ledger_hold_id')
        batch_op.drop_column('ledger_account_id')
        batch_op.drop_column('external_amount_msat')
        batch_op.drop_column('internal_amount_msat')
        batch_op.create_check_constraint(
            'ck_checkout_sessions_status_valid',
            "status IN ('created', 'settled', 'failed', 'canceled', "
            "'expired')",
        )
    op.drop_index(op.f('ix_user_ledger_accounts_user_sub'), table_name='user_ledger_accounts')
    op.drop_index(op.f('ix_user_ledger_accounts_ledger_account_id'), table_name='user_ledger_accounts')
    op.drop_table('user_ledger_accounts')
    # ### end Alembic commands ###
